// Generated by Cadence Encounter(R) RTL Compiler RC14.21 - v14.20-s008_1
tclmode
set env(RC_VERSION) "RC14.21 - v14.20-s008_1"
vpxmode
set dofile abort exit
usage -auto -elapse
set log file ./lec_fe.log -replace
tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
vpxmode
tclmode
set env(CDN_SYNTH_ROOT) /net/edatools/cadence/rc/14.21.000-ISR1/tools.lnx86
set CDN_SYNTH_ROOT /net/edatools/cadence/rc/14.21.000-ISR1/tools.lnx86
vpxmode
tclmode
if {$ver >= 08.10} {
  vpx set naming style rc
}
vpxmode
set naming rule "_" "_" -array_delimiter -golden
set naming rule "%s[%d]" -instance_array
set naming rule "%s_reg" -register -golden
set naming rule "%L.%s" "%L[%d].%s" "%s" -instance
set naming rule "%L.%s" "%L[%d].%s" "%s" -variable
set undefined cell black_box -noascend -both
set hdl options -VERILOG_INCLUDE_DIR "sep:src:cwd"
set undriven signal Z -golden

add search path -library . /net/edatools/cadence/rc/14.21.000-ISR1/tools.lnx86/lib/tech
read library -statetable -liberty -both  \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_lvt_c30/r9p0/lib/sc12mc_cmos28hpp_base_lvt_c30_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_lvt_c34/r9p0/lib/sc12mc_cmos28hpp_base_lvt_c34_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_rvt_c30/r9p0/lib-ccs-tn/sc12mc_cmos28hpp_base_rvt_c30_ssa_nominal_max_0p765v_0c.lib_ccs_tn \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_rvt_c34/r9p0/lib/sc12mc_cmos28hpp_base_rvt_c34_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_rvt_c38/r9p0/lib/sc12mc_cmos28hpp_base_rvt_c38_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_hvt_c30/r9p0/lib/sc12mc_cmos28hpp_base_hvt_c30_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_hvt_c34/r9p0/lib/sc12mc_cmos28hpp_base_hvt_c34_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_base_hvt_c38/r9p0/lib/sc12mc_cmos28hpp_base_hvt_c38_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_pmk_rvt_c30/r9p0/lib/sc12mc_cmos28hpp_pmk_rvt_c30_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_pmk_rvt_c34/r9p0/lib/sc12mc_cmos28hpp_pmk_rvt_c34_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_pmk_rvt_c38/r9p0/lib/sc12mc_cmos28hpp_pmk_rvt_c38_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_pmk_hvt_c34/r9p0/lib/sc12mc_cmos28hpp_pmk_hvt_c34_ssa_nominal_max_0p765v_0c.lib \
	/net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_pmk_hvt_c38/r9p0/lib/sc12mc_cmos28hpp_pmk_hvt_c38_ssa_nominal_max_0p765v_0c.lib \
        /net/tdk/arm/gf/cmos28hpp/logic_ip/sc12mc_eco_rvt_c30/r9p0/lib/sc12mc_cmos28hpp_eco_rvt_c30_ssa_nominal_max_0p765v_0c.lib

add search path -design .
tclmode
if {$ver < 13.10} {
vpx read design  -verilog  -define SYNTHESIS  -golden -lastmod -noelab \
	-unzip ./rc/fe.mapped.dft.v.gz
} else {
vpx read design  -verilog95  -define SYNTHESIS  -merge bbox -golden -lastmod -noelab \
	-unzip ./rc/fe.mapped.dft.v.gz
}
vpxmode

elaborate design -golden -root fe -rootonly

tclmode
if {$ver < 13.10} {
vpx read design -verilog -revised -lastmod -noelab \
	-unzip ./edi/fe_signoff.v.gz
} else {
vpx read design -verilog95 -revised -lastmod -noelab \
	-unzip ./edi/fe_signoff.v.gz
}
vpxmode

elaborate design -revised -root fe

tclmode
set ver [lindex [split [lindex [get_version_info] 0] "-"] 0]
if {$ver < 13.10} {
vpx substitute blackbox model -golden
}
vpxmode
report design data
report black box

uniquify -all -nolib
set flatten model -seq_constant -seq_constant_x_to 0
set flatten model -nodff_to_dlat_zero -nodff_to_dlat_feedback
set parallel option -threads 4 -license xl -norelease_license
// set compare options -threads 0


//Table of test_signals and related attribues
//
// Index  Pin                            Type             Dedicated  Has_fanout  Port/Pin    special test function      Dft_auto_created      User_defined  LEC_value                      
//----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------  
// 1      rst_async_n                    test_mode        true       true        port        none                       false                 true          auto       
// 2      sc_cpren                       test_mode        true       false       port        compression_enable         true                  true          auto       
// 3      sc_spren                       test_mode        true       false       port        spreader                   true                  true          auto       
// 4      sc_sen                         shift_enable     true       false       port        none                       true                  true          auto       
//--------------------------------------------------------------------------------------------------------------------------------------------------------------------------  

add pin constraints 0 sc_sen -both //add pin constraints 0 sc_sen -revised
//add ignored outputs sc_do0 -revised
//add ignored outputs sc_do1 -revised
//add ignored outputs sc_do2 -revised
//add ignored outputs sc_do3 -revised
//add ignored outputs sc_do4 -revised
set analyze option -auto

write hier_compare dofile hier_lec_fe.do \
	-noexact_pin_match -constraint -usage -replace -balanced_extraction -input_output_pin_equivalence \
	-prepend_string "analyze datapath -module -verbose; usage; analyze datapath  -verbose"
run hier_compare hier_lec_fe.do -dynamic_hierarchy
// report hier_compare result -dynamicflattened
set system mode lec
tclmode
puts "No of diff points    = [get_compare_points -NONequivalent -count]"
if {[get_compare_points -NONequivalent -count] > 0} {
    puts "------------------------------------"
    puts "ERROR: Different Key Points detected"
    puts "------------------------------------"
#     foreach i [get_compare_points -NONequivalent] {
#         vpx report test vector [get_keypoint $i]
#         puts "     ----------------------------"
#     }
}
vpxmode
report statistics
exit -force
