###############################################################
#  Generated by:      Cadence Innovus 16.21-s078_1
#  OS:                Linux x86_64(Host ID serv175)
#  Generated on:      Mon Apr 16 13:22:04 2018
#  Design:            fe
#  Command:           create_ccopt_clock_tree_spec -file ../../script/innovus/ccopt_spec.tcl
###############################################################
#-------------------------------------------------------------------------------
# Clock tree setup script - dialect: Innovus
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------

namespace eval ::ccopt {}
namespace eval ::ccopt::ilm {}
set ::ccopt::ilm::ccoptSpecRestoreData {}
# Start by checking for unflattened ILMs.
# Will flatten if so and then check the db sync.
if { [catch {ccopt_check_and_flatten_ilms_no_restore}] } {
  return -code error
}
# cache the value of the restore command output by the ILM flattening code
set ::ccopt::ilm::ccoptSpecRestoreData $::ccopt::ilm::ccoptRestoreILMState

# Input pins determined constant across all timing configs.
set_ccopt_property case_analysis -pin uu_fft512_hi_lo_clk_gate_r_data_reg_0_/latch/SE 0

# Clocks present at pin clk
#   clk (period 1.960ns) in timing_config functional([/dh_eldorado/projects/400zr/workspaces/jacqueline.mertes/fe/backend/db/innovus/fe_place.enc.dat/mmmc/modes/functional/functional.sdc])
#   clk_sclk_shift (period 100.000ns) in timing_config scan_shift([/dh_eldorado/projects/400zr/workspaces/jacqueline.mertes/fe/backend/db/innovus/fe_place.enc.dat/mmmc/modes/scan_shift/scan_shift.sdc])
create_ccopt_clock_tree -name clk -source clk -no_skew_group
set_ccopt_property target_max_trans_sdc -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -early -clock_tree clk 0.100

set_ccopt_property target_max_trans_sdc -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -late -clock_tree clk 0.100

set_ccopt_property target_max_trans_sdc -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -early -clock_tree clk 0.100

set_ccopt_property target_max_trans_sdc -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -late -clock_tree clk 0.100
set_ccopt_property source_driver -clock_tree clk {BUF_X4B_A12TH_C34/A BUF_X4B_A12TH_C34/Y}
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_125c_libset_FuncRCmin_125c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_0c_libset_FuncRCmin_0c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_125c_libset_FuncRCmin_125c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_0c_libset_FuncRCmin_0c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_125c_libset_FuncRCmin_125c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_0c_libset_FuncRCmin_0c -early -clock_tree clk 0.005
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_m40c_libset_FuncRCmax_0c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ssa_0p81v_125c_libset_FuncRCmax_125c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_125c_libset_FuncRCmin_125c -late -clock_tree clk 0.340
set_ccopt_property source_input_max_trans -delay_corner ffa_0p945v_0c_libset_FuncRCmin_0c -late -clock_tree clk 0.340
set_ccopt_property source_max_capacitance -clock_tree clk 0.300
# Clock period setting for source pin of clk
set_ccopt_property clock_period -pin clk 1.96

# Skew group to balance non generated clock:clk in timing_config:functional (sdc /dh_eldorado/projects/400zr/workspaces/jacqueline.mertes/fe/backend/db/innovus/fe_place.enc.dat/mmmc/modes/functional/functional.sdc)
create_ccopt_skew_group -name clk/functional -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk/functional true
set_ccopt_property extracted_from_clock_name -skew_group clk/functional clk
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk/functional functional
set_ccopt_property extracted_from_delay_corners -skew_group clk/functional {ssa_0p81v_m40c_libset_FuncRCmax_0c ssa_0p81v_125c_libset_FuncRCmax_125c ffa_0p945v_125c_libset_FuncRCmin_125c ffa_0p945v_0c_libset_FuncRCmin_0c}

# Skew group to balance non generated clock:clk_sclk_shift in timing_config:scan_shift (sdc /dh_eldorado/projects/400zr/workspaces/jacqueline.mertes/fe/backend/db/innovus/fe_place.enc.dat/mmmc/modes/scan_shift/scan_shift.sdc)
create_ccopt_skew_group -name clk_sclk_shift/scan_shift -sources clk -auto_sinks
set_ccopt_property include_source_latency -skew_group clk_sclk_shift/scan_shift true
set_ccopt_property extracted_from_clock_name -skew_group clk_sclk_shift/scan_shift clk_sclk_shift
set_ccopt_property extracted_from_constraint_mode_name -skew_group clk_sclk_shift/scan_shift scan_shift
set_ccopt_property extracted_from_delay_corners -skew_group clk_sclk_shift/scan_shift {ssa_0p81v_m40c_libset_FuncRCmax_0c ssa_0p81v_125c_libset_FuncRCmax_125c ffa_0p945v_125c_libset_FuncRCmin_125c ffa_0p945v_0c_libset_FuncRCmin_0c}


check_ccopt_clock_tree_convergence
# Restore the ILM status if possible
if { [get_ccopt_property auto_design_state_for_ilms] == 0 } {
  if {$::ccopt::ilm::ccoptSpecRestoreData != {} } {
    eval $::ccopt::ilm::ccoptSpecRestoreData
  }
}

